name: Automated Builds
on: [push, workflow_dispatch]
jobs:
  win32-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Generate Documentation
        run: cmake --build build -t doc --config Release
      - name: Archive Windows Package
        uses: actions/upload-artifact@v4
        with:
          name: tm_windows
          path: |
            tm.exe
            tm.html
            tm.ini
            tm_default.ini
  linux-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Prerequisites
        run: |
          sudo apt -y update
          sudo apt -y install cmake ninja-build libsdl2-dev
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -G Ninja
      - name: Build
        run: cmake --build build
      - name: Generate Documentation
        run: cmake --build build -t doc
      - name: Archive Linux Packages
        uses: actions/upload-artifact@v4
        with:
          name: tm_linux
          path: |
            tm
            tm.html
            tm.ini
            tm_default.ini
